In [1]:
import numpy as np

### 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [5]:
def is_none_of_the_elements_is_zero(arr):
    zeros = arr[arr == 0]
    return len(zeros) == 0

arr1 = np.array([1,2,3,4])
arr2 = np.array([0,1,2,3])

print("Does Array --> ", arr1 , "doesn't contain any zero element : " , is_none_of_the_elements_is_zero(arr1))
print("Does Array --> ", arr2 , "doesn't contain any zero element : " , is_none_of_the_elements_is_zero(arr2))


Does Array -->  [1 2 3 4] doesn't contain any zero element :  True
Does Array -->  [0 1 2 3] doesn't contain any zero element :  False


### 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [9]:
def any_element_nonzero(arr):
    zeros = arr[arr == 0]
    return not(len(zeros) == len(arr))

arr1 = np.array([0, 0, 0, 0])
arr2 = np.array([1, 0, 3, 0])

print("Is there is any non zero element is array --> ", arr1 , " : ", any_element_nonzero(arr1))
print("Is there is any non zero element is array --> ", arr2 , " : " ,any_element_nonzero(arr2))


Is there is any non zero element is array -->  [0 0 0 0]  :  False
Is there is any non zero element is array -->  [1 0 3 0]  :  True


### 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [20]:
def element_wise_comparison_with_tolerance(arr1, arr2, tol=0.00001):
    return np.allclose(arr1, arr2, atol=tol)

tol=0.00001

arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.0, 2.00001, 3.0])

print(arr1,"," , arr2 ,"are element-wise equal within tolerance" , "(",tol, ") ", ":", element_wise_comparison_with_tolerance(arr1, arr2))

arr3 = np.array([1.0, 2.0, 3.0])
arr4 = np.array([1.0, 2.1, 3.0])

print(arr3,"," , arr4 ,"\t       are element-wise equal within tolerance", "(",tol, ") ", ":", element_wise_comparison_with_tolerance(arr3, arr4))


[1. 2. 3.] , [1.      2.00001 3.     ] are element-wise equal within tolerance ( 1e-05 )  : True
[1. 2. 3.] , [1.  2.1 3. ] 	       are element-wise equal within tolerance ( 1e-05 )  : False


### 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [25]:
def create_array():
    zeros = np.zeros((1,10) , dtype = int)
    ones = np.ones((1,10) , dtype = int)
    fives = np.ones((1,10) , dtype = int) * 5
    arr = np.hstack((zeros,ones))
    arr = np.hstack((arr,fives))
    return arr

arr = create_array()
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5]])

### 5. Write a NumPy program to create an array of the integers from 30 to70.

In [26]:
arr = np.arange(30,71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

### 6. Write a NumPy program to create a 3x3 identity matrix

In [28]:
mat = np.zeros((3,3))
for i in range(mat.shape[0]):
    for j in range(mat.shape[1]):
        if i == j:
            mat[i][j] = 1
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Or

In [29]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 7. Write a NumPy program to generate a random number between 0 and 1

In [30]:
rand = np.random.random()
rand

0.3045729295177261

### 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [31]:
rand = np.random.normal(size=15)
rand

array([-1.255249  ,  2.04313523, -2.26117912, -0.4363762 ,  0.78576113,
       -0.15648489,  0.8421013 ,  1.14946978,  0.70189374, -1.58610508,
        1.24334354, -1.1730376 ,  0.26421568, -0.75211385,  0.63062199])

### 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [34]:
arr = np.arange(15,56)
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

### 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [35]:
arr = np.random.randint(0, 11, size=5)
arr

array([9, 5, 9, 1, 1])

### 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [38]:
arr = np.ones((10,10) , dtype = int)
arr[1:-1 , 1:-1] = np.zeros((8,8), dtype = int)
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,3, 4, 5.

In [39]:
arr = np.zeros((5,5) , dtype = int)
np.fill_diagonal(arr, [1, 2, 3, 4, 5])
arr


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.


In [41]:
arr = np.zeros((4, 4))

for i in range(arr.shape[0]):
    for j in range(arr.shape[0]):
        if (i + j) % 2 != 0: 
            arr[i, j] = 1

arr


array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

### 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz for

In [42]:
arr1 = np.array([1, 2, 3, 4])
arr1 = np.array([5, 6, 7, 8])

np.savez_compressed('arrays.npz', array1=arr1, array2=arr2)

### 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.

In [43]:
rand = np.random.rand(40)
rand

array([0.51123707, 0.85892241, 0.5869985 , 0.45781141, 0.59062832,
       0.51468303, 0.47792487, 0.35531777, 0.39747028, 0.6339114 ,
       0.04115014, 0.85810823, 0.21509868, 0.17483393, 0.30769515,
       0.75765504, 0.20709488, 0.32909936, 0.17360502, 0.14880253,
       0.95671541, 0.11276774, 0.78280223, 0.61354963, 0.23129961,
       0.25547004, 0.20310256, 0.01097945, 0.23820576, 0.90399303,
       0.01296419, 0.16591904, 0.73304232, 0.40714165, 0.00820462,
       0.07786394, 0.49561266, 0.16643426, 0.44724025, 0.02562876])

### 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [44]:
def extract_numbers(arr, threshold):

    less_than = arr[arr < threshold]
    greater_than = arr[arr > threshold]
    
    return less_than, greater_than


arr = np.array([1, 2, 3, 4, 5])
less_than, greater_than = extract_numbers(arr, 3)

print("Numbers less than", 3, ":", less_than)
print("Numbers greater than", 3, ":", greater_than)


Numbers less than 3 : [1 2]
Numbers greater than 3 : [4 5]
